# Generated by Django 4.2.7 on 2023-12-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumodel",
            name="model_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Model Name"
            ),
        ),
    ]
