# Generated by Django 4.2.7 on 2023-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0002_menumodel_model_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menumodel",
            name="model_name",
        ),
        migrations.AddField(
            model_name="menumodel",
            name="model",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Model"
            ),
        ),
    ]
