# Generated by Django 4.2.7 on 2023-12-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0003_remove_menumodel_model_name_menumodel_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumodel",
            name="form_component_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Form Component Name",
            ),
        ),
    ]
