# Generated by Django 4.2.7 on 2023-12-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0004_menumodel_form_component_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menumodel",
            name="app",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Belong to App",
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="component_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Component Name",
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="form_component_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Form Component Name",
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="icon",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="is_hidden",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Hidden"
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="level",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(0, "根"), (1, "一级菜单"), (2, "二级菜单"), (3, "三级菜单")],
                default=1,
                null=True,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="menu_order",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="model",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="Model"
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="parent_id",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Parent Menu ID"
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="remark",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="Remark"
            ),
        ),
        migrations.AlterField(
            model_name="menumodel",
            name="url",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True, verbose_name="Url"
            ),
        ),
    ]
