# Generated by Django 4.2.7 on 2023-12-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "permissions",
            "0005_alter_menumodel_app_alter_menumodel_component_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="menumodel",
            name="is_form",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Form"
            ),
        ),
    ]
