# Generated by Django 4.2.7 on 2023-12-09 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0006_menumodel_is_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="menumodel",
            name="uniq_key",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(6)],
                verbose_name="UUID",
            ),
        ),
    ]
