# Generated by Django 4.2.7 on 2023-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0007_menumodel_uniq_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolegroupmodel",
            name="desc",
            field=models.CharField(
                blank=True, default="", max_length=500, null=True, verbose_name="Desc"
            ),
        ),
        migrations.AlterField(
            model_name="rolegroupmodel",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True, verbose_name="Name"
            ),
        ),
    ]
