# Generated by Django 4.2.7 on 2023-12-19 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersmodel",
            options={
                "ordering": ["-id"],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
    ]
